// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['ui']['App']['Greet'](arg1);
}

export function Prompt(arg1) {
  return window['go']['ui']['App']['Prompt'](arg1);
}

export function StartServer() {
  return window['go']['ui']['App']['StartServer']();
}
